# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Hand.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'Hand.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nHand.proto\x12\x0chand_control\"\x9b\x01\n\x0eGestureRequest\x12\x39\n\x07gesture\x18\x01 \x01(\x0e\x32(.hand_control.GestureRequest.GestureType\"N\n\x0bGestureType\x12\x08\n\x04ROCK\x10\x00\x12\x0c\n\x08SCISSORS\x10\x01\x12\t\n\x05PAPER\x10\x02\x12\x0f\n\x0bPENCIL_GRIP\x10\x03\x12\x0b\n\x07NEUTRAL\x10\x04\"\xb9\x01\n\x0fGestureResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12L\n\x10\x66inger_positions\x18\x03 \x03(\x0b\x32\x32.hand_control.GestureResponse.FingerPositionsEntry\x1a\x36\n\x14\x46ingerPositionsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32P\n\x04Hand\x12H\n\x07Gesture\x12\x1c.hand_control.GestureRequest\x1a\x1d.hand_control.GestureResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Hand_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GESTURERESPONSE_FINGERPOSITIONSENTRY']._loaded_options = None
  _globals['_GESTURERESPONSE_FINGERPOSITIONSENTRY']._serialized_options = b'8\001'
  _globals['_GESTUREREQUEST']._serialized_start=29
  _globals['_GESTUREREQUEST']._serialized_end=184
  _globals['_GESTUREREQUEST_GESTURETYPE']._serialized_start=106
  _globals['_GESTUREREQUEST_GESTURETYPE']._serialized_end=184
  _globals['_GESTURERESPONSE']._serialized_start=187
  _globals['_GESTURERESPONSE']._serialized_end=372
  _globals['_GESTURERESPONSE_FINGERPOSITIONSENTRY']._serialized_start=318
  _globals['_GESTURERESPONSE_FINGERPOSITIONSENTRY']._serialized_end=372
  _globals['_HAND']._serialized_start=374
  _globals['_HAND']._serialized_end=454
# @@protoc_insertion_point(module_scope)
