# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import sys
import os
current_dir = os.path.dirname(os.path.abspath(__file__))
sys.path.append(current_dir)
import template_pb2 as template__pb2


class GRPCGlobalVariableTaskStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetInt = channel.unary_unary(
                '/GRPCGlobalVariable.GRPCGlobalVariableTask/SetInt',
                request_serializer=template__pb2.GInt.SerializeToString,
                response_deserializer=template__pb2.Empty.FromString,
                )
        self.GetInt = channel.unary_unary(
                '/GRPCGlobalVariable.GRPCGlobalVariableTask/GetInt',
                request_serializer=template__pb2.IntVal.SerializeToString,
                response_deserializer=template__pb2.IntVal.FromString,
                )
        self.SetInts = channel.unary_unary(
                '/GRPCGlobalVariable.GRPCGlobalVariableTask/SetInts',
                request_serializer=template__pb2.GInts.SerializeToString,
                response_deserializer=template__pb2.Empty.FromString,
                )
        self.GetInts = channel.unary_unary(
                '/GRPCGlobalVariable.GRPCGlobalVariableTask/GetInts',
                request_serializer=template__pb2.GInt.SerializeToString,
                response_deserializer=template__pb2.IntVals.FromString,
                )


class GRPCGlobalVariableTaskServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SetInt(self, request, context):
        """Global variables
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetInts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GRPCGlobalVariableTaskServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetInt': grpc.unary_unary_rpc_method_handler(
                    servicer.SetInt,
                    request_deserializer=template__pb2.GInt.FromString,
                    response_serializer=template__pb2.Empty.SerializeToString,
            ),
            'GetInt': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInt,
                    request_deserializer=template__pb2.IntVal.FromString,
                    response_serializer=template__pb2.IntVal.SerializeToString,
            ),
            'SetInts': grpc.unary_unary_rpc_method_handler(
                    servicer.SetInts,
                    request_deserializer=template__pb2.GInts.FromString,
                    response_serializer=template__pb2.Empty.SerializeToString,
            ),
            'GetInts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInts,
                    request_deserializer=template__pb2.GInt.FromString,
                    response_serializer=template__pb2.IntVals.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'GRPCGlobalVariable.GRPCGlobalVariableTask', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GRPCGlobalVariableTask(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SetInt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCGlobalVariable.GRPCGlobalVariableTask/SetInt',
            template__pb2.GInt.SerializeToString,
            template__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetInt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCGlobalVariable.GRPCGlobalVariableTask/GetInt',
            template__pb2.IntVal.SerializeToString,
            template__pb2.IntVal.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetInts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCGlobalVariable.GRPCGlobalVariableTask/SetInts',
            template__pb2.GInts.SerializeToString,
            template__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetInts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCGlobalVariable.GRPCGlobalVariableTask/GetInts',
            template__pb2.GInt.SerializeToString,
            template__pb2.IntVals.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
